# charada_data.py
CHARADA = {
    "01": "Caballo, Sol, Fidelidad, Tinta", "02": "Mariposa, Dinero, Hombre, Cafetera",
    "03": "Marinero, Luna, Taza, Ciempiés", "04": "Gato, Zapato, Llave, Vela",
    "05": "Monja, Mar, Periódico, Armario", "06": "Tortuga, Reverbero, Carta, Espejuelos",
    "07": "Caracol, Mierda, Sueño, Pañuelo", "08": "Muerto, Calabaza, León, Sortija",
    "09": "Elefante, Entierro, Lira, Balde", "10": "Pescado, Cazuela, Árbol, Billete",
    "11": "Gallo, Lluvia, Fábrica, Pañuelo", "12": "Mujer, Ballena, Vieja, Cometa",
    "13": "Pavón, Anafe, Elefante, Niña", "14": "Cementerio, Tigre, Sartén, Gato",
    "15": "Perro, Niña, Visita, Cuchara", "16": "Toro, Plancha, Vestido, Incendio",
    "17": "Luna, San Lázaro, Armas, Camisón", "18": "Pescado chico, Iglesia, Sirena, Palma",
    "19": "Lombriz, Bandera, Mesa, Fusil", "20": "Gato fino, Orinal, Tiburón, Cañón",
    "21": "Majá, Chaleco, Cotorra, Reloj", "22": "Sapo, Estrella, Lirios, Carruaje",
    "23": "Vapor, Escalera, Submarino, Navaja", "24": "Paloma, Música, Cocina, Reloj",
    "25": "Casa, Piedra frita, Sol, Objetos", "26": "Anguila, Calle, Médico, Brillante",
    "27": "Avispa, Campana, Canario, Baúl", "28": "Chivo, Perro, Político, Maleta",
    "29": "Ratón, Nube, Venado, Reloj", "30": "Camarón, Almanaque, Arco iris, Monja",
    "31": "Zapato, Venado, Escuela, Limosnero", "32": "Cochino, Espejo, Reloj, Mula",
    "33": "Tiña, Jesucristo, Barco, Abanico", "34": "Mono, Familia, Negro, Sombrero",
    "35": "Araña, Novia, Mosquito, Tinaja", "36": "Bodega, Pipa, Ómnibus, Pajarito",
    "37": "Bruja, Gallina, Hormiga, Piedra", "38": "Macao, Guantes, Dinero, Tambor",
    "39": "Culebra, Rayo, Conejo, Comida", "40": "Cura, Sangre, Cantante, Estatua",
    "41": "Lagartija, Cárcel, Pato, Jubo", "42": "Pato, País, Joyas, Campana",
    "43": "Alacrán, Puerta, Preso, Piano", "44": "Año del Cuero, Infierno, Guácara, Reloj",
    "45": "Tiburón, Presidente, Maleta, Tranvía", "46": "Guajiro, Humo, Autobús, Salto",
    "47": "Pájaro, Escoba, Mala noticia, Reloj", "48": "Cucaracha, Abanico, Barbero, Cubo",
    "49": "Borracho, Riqueza, Lupa, Percha", "50": "Policía, Agua, Flor, Joyas",
    "51": "Soldado, Sed, Sereno, Anteojos", "52": "Bicicleta, Coche, Libreta, Borracho",
    "53": "Luz eléctrica, Beso, Diamante, Tragedia", "54": "Flores, Gallina, Sueño, Cañón",
    "55": "Cangrejo, Baile, Iglesia, Murciélago", "56": "Reina, Merengue, Piedra, Carreta",
    "57": "Cama, Telegrama, Puerta, Granizo", "58": "Adulterio, Retrato, Cuchillo, Balde",
    "59": "Loco, Calavera, Comida, Langosta", "60": "Payaso, Huevo, Sol, Ave",
    "61": "Caballo grande, Arroz, Cañón, Escopeta", "62": "Benjamín, Matrimonio, Lámpara, Nieve",
    "63": "Asesino, Escalera, Cuernos, Caracol", "64": "Muerto grande, Tiroteo, Reloj, Cama",
    "65": "Cárcel, Comida, Trueno, Conejo", "66": "Divorcio, Tarros, Ómnibus, Pozo",
    "67": "Puñalada, Hospital, Reloj, Alacrán", "68": "Cementerio, Títere, Dinero, Maleta",
    "69": "Pozo, Novia, Loma, Vagos", "70": "Teléfono, Coco, Arco iris, Bala",
    "71": "Río, Sombrero, Perro, Fusil", "72": "Buey, Collar, Cetro, Ferrocarril",
    "73": "Navaja, Parque, Ajedrez, Maleta", "74": "Papalote, Militar, Serpiente, Ruleta",
    "75": "Cine, Corbata, Flores, Viento", "76": "Bailarina, Hierro, Caja, Violín",
    "77": "Banderas, Muletas, Camino, Granizo", "78": "Sarcófago, Rey, Obispo, Lunares",
    "79": "Coche, Abogado, Lagarto, Tren", "80": "Médico, Teléfono, Vieja, Trompeta",
    "81": "Teatro, Ingenio, Cuerda, Pato", "82": "Madre, León, Estrella, Bote",
    "83": "Tragedia, Bastón, Limosnero, Madera", "84": "Ciego, Sastre, Banquete, Cuadros",
    "85": "Espejo, Reloj, Águila, Zapato", "86": "Tijeras, Convento, Manguera, Desnudo",
    "87": "Plátano, Fuego, Nueva York, Baúl", "88": "Espejuelos, Aduana, Hojas, Papa",
    "89": "Lotería, Casa vieja, Agua, Melón", "90": "Viejo, Espejo, Trueno, Caramelos",
    "91": "Alpargata, Comunista, Pájaro, Bolsa", "92": "Globo, Avión, Globo grande, Cuba",
    "93": "Sortija, Revolución, Joyas, Andarín", "94": "Machete, Habana, Mariposa, Flores",
    "95": "Guerra, Cuchillo, Perro, Zapato", "96": "Desafío, Zapato, Puta, Pájaro",
    "97": "Grillo, Mosquito, Limosnero, Viejo", "98": "Piano, Santo, Entierro, Traición",
    "99": "Carbonero, Gallo, Sereno, Temporal", "00": "Huevos, Dinero, Rueda, Inodoro"
}
